name: Windmill Monitor

on:
  schedule:
    - cron: '*/5 * * * *' # ஒவ்வொரு 5 நிமிடத்திற்கு ஒருமுறை ஆட்டோமேட்டிக்காக ரன் ஆகும்
  workflow_dispatch: # தேவைப்பட்டால் நீங்களே கைமுறையாகவும் ரன் செய்து கொள்ளலாம்

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium requests

      - name: Run Monitor Script
        env:
          SCADA_USER: ${{ secrets.SCADA_USER }}
          SCADA_PASS: ${{ secrets.SCADA_PASS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python windmill_monitor.py
