name: Windmill Monitor

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Restore counts cache
        uses: actions/cache@v4
        with:
          path: counts.json
          key: scada-counts-cache

      - name: Install dependencies
        run: |
          pip install selenium requests

      - name: Run Monitor Script
        env:
          SCADA_USER: ${{ secrets.SCADA_USER }}
          SCADA_PASS: ${{ secrets.SCADA_PASS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python windmill_monitor.py
